hostname = "DEVICEID"
local_gateway_hostname = "GATEWAYID"

trust_bundle_cert = "file:////etc/ssl/certs/azure-iot-test-only.root.ca.cert.pem.pem"

## Manual provisioning with X.509 certificate
[provisioning]
source = "manual"
iothub_hostname = "cayers-edge-dev.azure-devices.net"
device_id = "DEVICEID"
#
[provisioning.authentication]
method = "x509"
#
identity_cert = "file:///etc/aziot/certificates/iot-edge-device-identity-DEVICEID-primary-full-chain.cert.pem"                # file URI, or...
identity_pk = "file:///etc/aziot/certificates/iot-edge-device-identity-DEVICEID-primary.key.pem"